version: '3.8'

services:
  tagalog-dict-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tagalog-dict-api
    ports:
      - "8054:8054"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    
    restart: unless-stopped
    